run_mode: "ft"
load_model: True
load_dir: "/storage1/yinjie.tang/Active/feng.jiarui/GOFA/cache_data/best_ckpt_3.pth"
last_epochs: 0
num_epochs: 1
mode: autoencoder
batch_size: 1
lr: 0.0001
l2: 0.0
selections: True
llm_max_length: 256

train_task_names:
  - arxiv
sample_size_per_task:
  - 10
hops:
  - 3

train_max_nodes_per_hops:
  - 5
ways: 5
instructs: True

eval_task_names:
  - cora_node

inf_sample_size_per_task:
  - 10

inf_hops:
  - 3

inf_max_nodes_per_hops:
  - 5

inf_ways:
  - 7

inf_instructs:
  - True

inf_selections:
  - True

dec_lora: True